### ISSUE TITLE
Operations: match commit hook versions to pyproject.toml versions

### ISSUE THREAD

**Issue by danwt** [informalsystems/modelator-py#2]
Bugs may creep in if versions are not kept aligned.

Here is a hook
```
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
        - id: mypy
```

The `rev` field should be appropriate.
